//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestoDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_cost_center
    {
        public int client_account_id { get; set; }
        public string client_account_name { get; set; }
        public string cost_center { get; set; }
        public int device_count { get; set; }
    }
}
