//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestoDataService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mls_dbEntities : DbContext
    {
        public mls_dbEntities()
            : base("name=mls_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<backup_agent> backup_agent { get; set; }
        public virtual DbSet<client_cost_center> client_cost_center { get; set; }
        public virtual DbSet<model_types_power> model_types_power { get; set; }
        public virtual DbSet<monitoring_agent> monitoring_agent { get; set; }
        public virtual DbSet<os_types> os_types { get; set; }
        public virtual DbSet<related_systems> related_systems { get; set; }
        public virtual DbSet<server_categories> server_categories { get; set; }
        public virtual DbSet<server_state> server_state { get; set; }
        public virtual DbSet<server_types> server_types { get; set; }
        public virtual DbSet<service_category> service_category { get; set; }
        public virtual DbSet<site_location> site_location { get; set; }
        public virtual DbSet<support_org> support_org { get; set; }
        public virtual DbSet<tko_msl_master> tko_msl_master { get; set; }
        public virtual DbSet<vm_platform> vm_platform { get; set; }
    }
}
