//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestoDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class model_types_power
    {
        public int model_type_id { get; set; }
        public string model_name { get; set; }
        public string device_count { get; set; }
        public string kw { get; set; }
        public string platform { get; set; }
    }
}
