//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestoDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class os_types
    {
        public int os_type_id { get; set; }
        public string os_name { get; set; }
        public string os_vendor { get; set; }
        public string os_type { get; set; }
        public string os_category { get; set; }
        public string server_count { get; set; }
    }
}
