//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestoDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class related_systems
    {
        public int related_systems_id { get; set; }
        public string system_category_name { get; set; }
    }
}
