//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestoDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_category
    {
        public int service_category_id { get; set; }
        public string service_category_name { get; set; }
        public Nullable<int> server_count { get; set; }
        public string impact { get; set; }
        public string urgency { get; set; }
    }
}
