//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestoDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class site_location
    {
        public int site_location_id { get; set; }
        public string site_location_name { get; set; }
        public Nullable<int> device_count { get; set; }
        public string total_measured { get; set; }
        public string kwh_measured { get; set; }
        public string google_map_address { get; set; }
    }
}
